---

- name: Install the python3-mysqldb
  apt:
     name: "{{ item }}"
     state: present
     update_cache: true
  with_items:
     - python3-mysqldb

- name: Create Database
  mysql_db:
    name: "{{ db_wp_name }}"
    login_user: root
    login_password: "{{ db_root_pass }}"
    login_host: localhost
    state: present

- name: Get list of MySQL users
  shell: "mysql -u root -p{{ db_root_pass }} -h localhost -e 'SHOW DATABASES;'"
  register: databases

- debug: 
    var: databases.stdout_lines

- name: Create user for {{ db_wp_name }}
  mysql_user:
    name: "{{ db_wp_user }}"
    password: "{{ db_user_wp_pass }}"
    host: '%'
    login_user: root
    login_password: "{{ db_root_pass }}"
    login_host: localhost
    state: present

- name: Get list of MySQL users
  shell: "mysql -u root -p{{ db_root_pass }} -h localhost -e 'SELECT user FROM mysql.user;'"
  register: mysql_users

- debug: 
    var: mysql_users.stdout_lines

- name: Grant privileges for {{ db_wp_user }} to {{ db_wp_name }} 
  mysql_user:
    name: "{{ db_wp_user }}"
    host: '%'
    priv: "{{ db_wp_name }}.*:ALL"
    login_user: root
    login_password: "{{ db_root_pass }}"
    login_host: localhost
    state: present

- name: Show grants of the {{ db_wp_user }}
  shell: "mysql -u root -p{{ db_root_pass }} -h localhost -e 'SHOW GRANTS FOR {{ db_wp_user }};'"
  register: user_grants

- debug: 
    var: user_grants.stdout_lines

- name: Show tables in {{ db_wp_name }} 
  shell: "mysql -u root -p{{ db_root_pass }} -h localhost -e 'SHOW TABLES IN {{ db_wp_name }};'"
  register: tables_in_khr_database

- debug:
     var: tables_in_khr_database.stdout_lines
