---
- name: Create directory for the Domain
  file:
    path: /var/www/khr_domain
    state: directory
    mode: '0755'

- name: Assing owership of the directory
  file:
    path: /var/www/khr_domain
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes