---
- name: Install Apache stack
  hosts: LINUX_1
  become: yes
  roles:
    - Apache

- name: Install Nginx stack
  hosts: LINUX_2
  become: yes
  roles:
    - Nginx

- name: Inastall Mysql Php 
  hosts: all
  become: yes
  roles:
     - Mysql
     - Php
     - Domain
     - Configure